name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run clean
    - run: git config --global user.name "farukcan"
    - run: git config --global user.email  "omer@farukcan.net"
    - run: npm run deploy
